name: Ejercicio 1

on:
  workflow_dispatch:

jobs:
  despliegue_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: 1.Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: 2. Copiar archivos a isntancia
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "/home/${{ secrets.USER }}/site"   

      # 2) Ejecutar comandos remotos: mover a carpeta web y reiniciar nginx
      - name: Move files to web dir and restart nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            sudo mkdir -p /var/www/my-site
            sudo cp -r /home/${{ secrets.USER }}/site/* /var/www/my-site/
            # permisos: prueba para Ubuntu/Nginx y AmazonLinux/Nginx
            sudo chown -R www-data:www-data /var/www/my-site 2>/dev/null | true
            sudo systemctl restart nginx || true
